# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java


trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
jobs:
- job: A
  steps:
  - task: Maven@3
    inputs:
      mavenOptions: '-Xmx3072m'
      jdkVersionOption: "1.8"
      jdkArchitectureoption: x64
      testResultsFiles: '**/surefire-reports/TEST-.xml'
      mavenPomFile: 'pom.xml'
      javaHomeOption: 'JDKVersion'
      publishJUnitResults: true
      goals: 'package'
 
- job: B
  steps:
  - template: ./temp.yml
